name: Test Workflow

on: ["workflow_dispatch"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'ruby', 'csharp', 'java-kotlin' ]
        # CodeQL supports [ 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift' ]
    steps:
      - name: Set FILENAME
        run: |
          if [[ ${{ matrix.language }} == 'java-kotlin' ]]; then
            echo "FILENAME=java" >> $GITHUB_ENV
          else
            echo "FILENAME=${{matrix.language}}" >> $GITHUB_ENV
          fi
      - name: Show FILENAME
        run: echo $FILENAME

          
  
