name: Test Workflow

on: ["workflow_dispatch"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift' ]
        # CodeQL supports [ 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift' ]
    steps:
      - name: Send Build Notification
        env:
          FILE_NAME: "${{ matrix.language == 'java-kotlin' && 'java' || matrix.language == 'c-cpp' && 'cpp' || '${{ matrix.language }}' }}"
        run: |
          echo FILE_NAME
          echo $FILE_NAME
  
